### ISSUE TITLE
CX Heap_Inspection @ Models/User.cs [feature-checkmarx]

### ISSUE THREAD

**Issue by Prevelate** [Prevelate/dotnetdemo#52]
**Heap_Inspection** issue exists @ **Models/User.cs** in branch **feature-checkmarx**

*Method } at line 29 of Models\User.cs defines&nbsp;password, which&nbsp;is designated to contain user passwords. However, while plaintext passwords are later assigned to password, this variable is never cleared from memory.*

Severity: Medium

CWE:244

[Checkmarx](http://N8Lab/CxWebClient/ViewerMain.aspx?scanid=1020026&projectid=10006&pathid=9)

[Recommended Fix](http://N8Lab/CxWebClient/ScanQueryDescription.aspx?queryID=3772&queryVersionCode=94864652&queryTitle=Heap_Inspection)

Lines: [29](https://github.com/Prevelate/dotnetdemo/blob/feature-checkmarx/Models/User.cs#L29) 

---
[Code (Line #29):](https://github.com/Prevelate/dotnetdemo/blob/feature-checkmarx/Models/User.cs#L29)
```
      public string password { get; set; }
```
---

**Comment by saradak562** [comment]
Same issue but iam doing in java, can I get any solutions for this?
